# from binance import Client



# api_key = ""
# api_secret = ""


# client = Client(api_key, api_secret)
# futures_exchange_info = client.futures_exchange_info() 


# for i in range(155):
#     print(futures_exchange_info['symbols'][i]['symbol'])

CRYPTO_LIST = ['BTCUSDTPERP','ETHUSDTPERP','BCHUSDTPERP','XRPUSDTPERP','EOSUSDTPERP','LTCUSDTPERP','TRXUSDTPERP','ETCUSDTPERP','LINKUSDTPERP','XLMUSDTPERP','ADAUSDTPERP','XMRUSDTPERP','DASHUSDTPERP','ZECUSDTPERP','XTZUSDTPERP','BNBUSDTPERP','ATOMUSDTPERP','ONTUSDTPERP','IOTAUSDTPERP','BATUSDTPERP','VETUSDTPERP','NEOUSDTPERP','QTUMUSDTPERP','IOSTUSDTPERP','THETAUSDTPERP','ALGOUSDTPERP','ZILUSDTPERP','KNCUSDTPERP','ZRXUSDTPERP','COMPUSDTPERP','OMGUSDTPERP','DOGEUSDTPERP','SXPUSDTPERP','KAVAUSDTPERP','BANDUSDTPERP','RLCUSDTPERP','WAVESUSDTPERP','MKRUSDTPERP','SNXUSDTPERP','DOTUSDTPERP','DEFIUSDTPERP','YFIUSDTPERP','BALUSDTPERP','CRVUSDTPERP','TRBUSDTPERP','RUNEUSDTPERP','SUSHIUSDTPERP','SRMUSDTPERP','EGLDUSDTPERP','SOLUSDTPERP','ICXUSDTPERP','STORJUSDTPERP','BLZUSDTPERP','UNIUSDTPERP','AVAXUSDTPERP','FTMUSDTPERP','HNTUSDTPERP','ENJUSDTPERP','FLMUSDTPERP','TOMOUSDTPERP','RENUSDTPERP','KSMUSDTPERP','NEARUSDTPERP','AAVEUSDTPERP','FILUSDTPERP','RSRUSDTPERP','LRCUSDTPERP','MATICUSDTPERP','OCEANUSDTPERP','CVCUSDTPERP','BELUSDTPERP','CTKUSDTPERP','AXSUSDTPERP','ALPHAUSDTPERP','ZENUSDTPERP','SKLUSDTPERP','GRTUSDTPERP','1INCHUSDTPERP','BTCBUSD','AKROUSDTPERP','CHZUSDTPERP','SANDUSDTPERP','ANKRUSDTPERP','LUNAUSDTPERP','BTSUSDTPERP','LITUSDTPERP','UNFIUSDTPERP','DODOUSDTPERP','REEFUSDTPERP','RVNUSDTPERP','SFPUSDTPERP','XEMUSDTPERP','BTCSTUSDTPERP','COTIUSDTPERP','CHRUSDTPERP','MANAUSDTPERP','ALICEUSDTPERP','HBARUSDTPERP','ONEUSDTPERP','LINAUSDTPERP','STMXUSDTPERP','DENTUSDTPERP','CELRUSDTPERP','HOTUSDTPERP','MTLUSDTPERP','OGNUSDTPERP','NKNUSDTPERP','SCUSDTPERP','DGBUSDTPERP','1000SHIBUSDTPERP','ICPUSDTPERP','BAKEUSDTPERP','GTCUSDTPERP','ETHBUSD','BTCDOMUSDTPERP','TLMUSDTPERP','BNBBUSD','ADABUSD','XRPBUSD','IOTXUSDTPERP','DOGEBUSD','AUDIOUSDTPERP','RAYUSDTPERP','C98USDTPERP','MASKUSDTPERP','ATAUSDTPERP','SOLBUSD','FTTBUSD','DYDXUSDTPERP','GALAUSDTPERP','CELOUSDTPERP','ARUSDTPERP','KLAYUSDTPERP','ARPAUSDTPERP','CTSIUSDTPERP','LPTUSDTPERP','ENSUSDTPERP','PEOPLEUSDTPERP','ANTUSDTPERP','ROSEUSDTPERP','DUSKUSDTPERP','FLOWUSDTPERP','IMXUSDTPERP','API3USDTPERP','ANCUSDTPERP','GMTUSDTPERP','APEUSDTPERP','BNXUSDTPERP','WOOUSDTPERP','FTTUSDTPERP','JASMYUSDTPERP','DARUSDTPERP']

CRYPTO_LIST_SHORT = ['BTCUSDTPERP','ETHUSDTPERP','BCHUSDTPERP','XRPUSDTPERP','EOSUSDTPERP']